export const DJ_RADIO_CHANGE_CATEGORY = 'DJ_RADIO_CHANGE_CATEGORY'
export const DJ_RADIO_CHANGE_CURRENT_ID = 'DJ_RADIO_CHANGE_CURRENT_ID'
export const DJ_RADIO_CHANGE_RECOMMEND = 'DJ_RADIO_CHANGE_RECOMMEND'
export const DJ_RADIO_CHANGE_TOP_LIST = 'DJ_RADIO_CHANGE_TOP_LIST'