export const PLAYER_CHANGE_CURRENT_SONG = 'PLAYER_CHANGE_CURRENT_SONG'
export const PLAYER_CHANGE_LIST = 'PLAYER_CHANGE_LIST'
export const PLAYER_CHANGE_CURRENT_SONG_INDEX = 'PLAYER_CHANGE_CURRENT_SONG_INDEX'
export const PLAYER_CHANGE_MODE = 'PLAYER_CHANGE_MODE'
export const PLAYER_CHANGE_LYRIC_LIST = 'PLAYER_CHANGE_LYRIC_LIST'
export const PLYAER_CHANGE_CURRENT_LYRIC_INDEX = 'PLYAER_CHANGE_CURRENT_LYRIC_INDEX'

export const PLAYER_CHANGE_SELECTED_SONG = "PLAYER_CHANGE_SELECTED_SONG"
export const PLAYER_CHANGE_SELECTED_SONG_LYRIC = 'PLAYER_CHANGE_SELECTED_SONG_LYRIC'
export const PLAYER_CHANGE_SIMI_PLAYLIST = "PLAYER_CHANGE_SIMI_PLAYLIST"
export const PLAYER_CHANGE_SIMI_SONGS = "PLAYER_CHANGE_SIMI_SONGS"
export const PLAYER_CHANGE_SELECTED_SONG_ID = 'PLAYER_CHANGE_SELECTED_SONG_ID'
