export const PLAYLIST_CHANGE_CATEGORY = 'PLAYLIST_CHANGE_CATEGORY'
export const PLAYLIST_CHANGE_CURRENT_CATEGORY = 'PLAYLIST_CHANGE_CURRENT_CATEGORY'
export const PLAYLIST_CHANGE_SONG_LIST = 'PLAYLIST_CHANGE_SONG_LIST'

export const PER_PAGE_NUMBER = 35